version: '3.9'
services:
  db:
    image: mongo:7
    container_name: db
    ports:
      - '27017:27017'
    restart: always

  rabbit:
    image: rabbitmq:3.12.1-management-alpine
    container_name: rabbit
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    restart: always

  gateway:
    image: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - '4000:80'
    environment:
      - PORT=80
      - RABBIT=amqp://test:test@rabbit:5672
    depends_on:
      - rabbit
    restart: 'no'

  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
      - '4001:80'
    environment:
      - PORT=80
      - RABBIT=amqp://test:test@rabbit:5672
    depends_on:
      - db
      - rabbit
    restart: 'no'

  video-upload:
    image: video-upload
    build:
      context: ./video-upload
      dockerfile: Dockerfile
    container_name: video-upload
    ports:
      - '4004:80'
    environment:
      - PORT=80
      - RABBIT=amqp://test:test@rabbit:5672
    depends_on:
      - rabbit
    restart: 'no'

  history:
    image: history
    build:
      context: ./history
      dockerfile: Dockerfile
    container_name: history
    ports:
      - '4002:80'
    environment:
      - PORT=80
      - RABBIT=amqp://test:test@rabbit:5672
      - DBHOST=mongodb://db:27017
      - DBNAME=history
    depends_on:
      - db
      - rabbit
    restart: 'no'

  #
  # Uncomment this service to enable cloud storage.
  #

  # video-storage:
  #   image: oci-storage
  #   build:
  #     context: ./oci-storage
  #     dockerfile: Dockerfile
  #   container_name: video-storage
  #   ports:
  #     - '4005:80'
  #   environment:
  #     - PORT=80
  #     - BUCKET_NAME=tuplus-bucket
  #     - NAMESPACE=cnqphqevfxnp
  #   restart: 'no'

  video-storage:
    image: azure-storage
    build:
      context: ./azure-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
      - '4005:80'
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT_NAME}
      - STORAGE_ACCESS_KEY=${STORAGE_ACCESS_KEY}
    restart: 'no'

  #
  # This is the local version of storage.
  #

  # video-storage:
  #   image: mock-storage
  #   build:
  #     context: ./mock-storage
  #     dockerfile: Dockerfile
  #   container_name: video-storage
  #   ports:
  #     - "4005:80"
  #   environment:
  #     - PORT=80
  #   restart: "no"

  metadata:
    image: metadata
    build:
      context: ./metadata
      dockerfile: Dockerfile
    container_name: metadata
    ports:
      - '4006:80'
    environment:
      - PORT=80
      - RABBIT=amqp://test:test@rabbit:5672
      - DBHOST=mongodb://db:27017
      - DBNAME=metadata
    depends_on:
      - db
      - rabbit
    restart: 'no'
