apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: video-streaming
  name: video-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-streaming
  strategy: {}
  template:
    metadata:
      labels:
        app: video-streaming
    spec:
      imagePullSecrets:
      - name: ocir-registry-secret
      containers:
      - image: ap-seoul-1.ocir.io/cnqphqevfxnp/video-streaming:20
        name: video-streaming
        # imagePullPolicy: Always
        env:
        - name: PORT
          value: "80"
        - name: DBHOST
          value: "mongodb://db:27017"
        - name: DBNAME
          value: "videos"
        - name: VIDEO_STORAGE
          value: "video-storage:80"
        - name: RABBIT
          value: "amqp://guest:guest@rabbit:5672"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: video-streaming
  name: video-streaming
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: video-streaming